# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /mnt/ECKernel/cmake-3.16.0-rc1/bin/cmake

# The command to remove a file.
RM = /mnt/ECKernel/cmake-3.16.0-rc1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/ECKernel/ec_gcm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/ECKernel/ec_gcm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/mnt/ECKernel/cmake-3.16.0-rc1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/mnt/ECKernel/cmake-3.16.0-rc1/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/ECKernel/ec_gcm/CMakeFiles /mnt/ECKernel/ec_gcm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/ECKernel/ec_gcm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ec_gcm

# Build rule for target.
ec_gcm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ec_gcm
.PHONY : ec_gcm

# fast build rule for target.
ec_gcm/fast:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/build
.PHONY : ec_gcm/fast

#=============================================================================
# Target rules for targets named loop_test

# Build rule for target.
loop_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 loop_test
.PHONY : loop_test

# fast build rule for target.
loop_test/fast:
	$(MAKE) -f CMakeFiles/loop_test.dir/build.make CMakeFiles/loop_test.dir/build
.PHONY : loop_test/fast

#=============================================================================
# Target rules for targets named tester

# Build rule for target.
tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tester
.PHONY : tester

# fast build rule for target.
tester/fast:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/build
.PHONY : tester/fast

ElasticContainer.o: ElasticContainer.cpp.o

.PHONY : ElasticContainer.o

# target to build an object file
ElasticContainer.cpp.o:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/ElasticContainer.cpp.o
.PHONY : ElasticContainer.cpp.o

ElasticContainer.i: ElasticContainer.cpp.i

.PHONY : ElasticContainer.i

# target to preprocess a source file
ElasticContainer.cpp.i:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/ElasticContainer.cpp.i
.PHONY : ElasticContainer.cpp.i

ElasticContainer.s: ElasticContainer.cpp.s

.PHONY : ElasticContainer.s

# target to generate assembly for a file
ElasticContainer.cpp.s:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/ElasticContainer.cpp.s
.PHONY : ElasticContainer.cpp.s

GlobalCloudManager.o: GlobalCloudManager.cpp.o

.PHONY : GlobalCloudManager.o

# target to build an object file
GlobalCloudManager.cpp.o:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/GlobalCloudManager.cpp.o
.PHONY : GlobalCloudManager.cpp.o

GlobalCloudManager.i: GlobalCloudManager.cpp.i

.PHONY : GlobalCloudManager.i

# target to preprocess a source file
GlobalCloudManager.cpp.i:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/GlobalCloudManager.cpp.i
.PHONY : GlobalCloudManager.cpp.i

GlobalCloudManager.s: GlobalCloudManager.cpp.s

.PHONY : GlobalCloudManager.s

# target to generate assembly for a file
GlobalCloudManager.cpp.s:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/GlobalCloudManager.cpp.s
.PHONY : GlobalCloudManager.cpp.s

Manager.o: Manager.cpp.o

.PHONY : Manager.o

# target to build an object file
Manager.cpp.o:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/Manager.cpp.o
.PHONY : Manager.cpp.o

Manager.i: Manager.cpp.i

.PHONY : Manager.i

# target to preprocess a source file
Manager.cpp.i:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/Manager.cpp.i
.PHONY : Manager.cpp.i

Manager.s: Manager.cpp.s

.PHONY : Manager.s

# target to generate assembly for a file
Manager.cpp.s:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/Manager.cpp.s
.PHONY : Manager.cpp.s

Server.o: Server.cpp.o

.PHONY : Server.o

# target to build an object file
Server.cpp.o:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/Server.cpp.o
.PHONY : Server.cpp.o

Server.i: Server.cpp.i

.PHONY : Server.i

# target to preprocess a source file
Server.cpp.i:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/Server.cpp.i
.PHONY : Server.cpp.i

Server.s: Server.cpp.s

.PHONY : Server.s

# target to generate assembly for a file
Server.cpp.s:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/Server.cpp.s
.PHONY : Server.cpp.s

SubContainer.o: SubContainer.cpp.o

.PHONY : SubContainer.o

# target to build an object file
SubContainer.cpp.o:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/SubContainer.cpp.o
.PHONY : SubContainer.cpp.o

SubContainer.i: SubContainer.cpp.i

.PHONY : SubContainer.i

# target to preprocess a source file
SubContainer.cpp.i:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/SubContainer.cpp.i
.PHONY : SubContainer.cpp.i

SubContainer.s: SubContainer.cpp.s

.PHONY : SubContainer.s

# target to generate assembly for a file
SubContainer.cpp.s:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/SubContainer.cpp.s
.PHONY : SubContainer.cpp.s

container_handler.o: container_handler.cpp.o

.PHONY : container_handler.o

# target to build an object file
container_handler.cpp.o:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/container_handler.cpp.o
.PHONY : container_handler.cpp.o

container_handler.i: container_handler.cpp.i

.PHONY : container_handler.i

# target to preprocess a source file
container_handler.cpp.i:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/container_handler.cpp.i
.PHONY : container_handler.cpp.i

container_handler.s: container_handler.cpp.s

.PHONY : container_handler.s

# target to generate assembly for a file
container_handler.cpp.s:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/container_handler.cpp.s
.PHONY : container_handler.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/main.cpp.s
.PHONY : main.cpp.s

tests/run_continuous.o: tests/run_continuous.cpp.o

.PHONY : tests/run_continuous.o

# target to build an object file
tests/run_continuous.cpp.o:
	$(MAKE) -f CMakeFiles/loop_test.dir/build.make CMakeFiles/loop_test.dir/tests/run_continuous.cpp.o
.PHONY : tests/run_continuous.cpp.o

tests/run_continuous.i: tests/run_continuous.cpp.i

.PHONY : tests/run_continuous.i

# target to preprocess a source file
tests/run_continuous.cpp.i:
	$(MAKE) -f CMakeFiles/loop_test.dir/build.make CMakeFiles/loop_test.dir/tests/run_continuous.cpp.i
.PHONY : tests/run_continuous.cpp.i

tests/run_continuous.s: tests/run_continuous.cpp.s

.PHONY : tests/run_continuous.s

# target to generate assembly for a file
tests/run_continuous.cpp.s:
	$(MAKE) -f CMakeFiles/loop_test.dir/build.make CMakeFiles/loop_test.dir/tests/run_continuous.cpp.s
.PHONY : tests/run_continuous.cpp.s

tests/run_test.o: tests/run_test.cpp.o

.PHONY : tests/run_test.o

# target to build an object file
tests/run_test.cpp.o:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/tests/run_test.cpp.o
.PHONY : tests/run_test.cpp.o

tests/run_test.i: tests/run_test.cpp.i

.PHONY : tests/run_test.i

# target to preprocess a source file
tests/run_test.cpp.i:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/tests/run_test.cpp.i
.PHONY : tests/run_test.cpp.i

tests/run_test.s: tests/run_test.cpp.s

.PHONY : tests/run_test.s

# target to generate assembly for a file
tests/run_test.cpp.s:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/tests/run_test.cpp.s
.PHONY : tests/run_test.cpp.s

types/msg.o: types/msg.cpp.o

.PHONY : types/msg.o

# target to build an object file
types/msg.cpp.o:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/types/msg.cpp.o
	$(MAKE) -f CMakeFiles/loop_test.dir/build.make CMakeFiles/loop_test.dir/types/msg.cpp.o
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/types/msg.cpp.o
.PHONY : types/msg.cpp.o

types/msg.i: types/msg.cpp.i

.PHONY : types/msg.i

# target to preprocess a source file
types/msg.cpp.i:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/types/msg.cpp.i
	$(MAKE) -f CMakeFiles/loop_test.dir/build.make CMakeFiles/loop_test.dir/types/msg.cpp.i
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/types/msg.cpp.i
.PHONY : types/msg.cpp.i

types/msg.s: types/msg.cpp.s

.PHONY : types/msg.s

# target to generate assembly for a file
types/msg.cpp.s:
	$(MAKE) -f CMakeFiles/ec_gcm.dir/build.make CMakeFiles/ec_gcm.dir/types/msg.cpp.s
	$(MAKE) -f CMakeFiles/loop_test.dir/build.make CMakeFiles/loop_test.dir/types/msg.cpp.s
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/types/msg.cpp.s
.PHONY : types/msg.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ec_gcm"
	@echo "... loop_test"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tester"
	@echo "... ElasticContainer.o"
	@echo "... ElasticContainer.i"
	@echo "... ElasticContainer.s"
	@echo "... GlobalCloudManager.o"
	@echo "... GlobalCloudManager.i"
	@echo "... GlobalCloudManager.s"
	@echo "... Manager.o"
	@echo "... Manager.i"
	@echo "... Manager.s"
	@echo "... Server.o"
	@echo "... Server.i"
	@echo "... Server.s"
	@echo "... SubContainer.o"
	@echo "... SubContainer.i"
	@echo "... SubContainer.s"
	@echo "... container_handler.o"
	@echo "... container_handler.i"
	@echo "... container_handler.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tests/run_continuous.o"
	@echo "... tests/run_continuous.i"
	@echo "... tests/run_continuous.s"
	@echo "... tests/run_test.o"
	@echo "... tests/run_test.i"
	@echo "... tests/run_test.s"
	@echo "... types/msg.o"
	@echo "... types/msg.i"
	@echo "... types/msg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

